In [1]:
import numpy as np

In [2]:

#start


In [3]:
array=np.array([[1,2,3],
               [2,3,4]])

print(array)
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size:',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


In [4]:

#numpy 创建数组


In [5]:
a=np.array([2,23,0],dtype=np.int16)                 #dtype: 定义数据类型
print(a)  

[ 2 23  0]


In [6]:
a1=np.array([[2,23,0],
             [24,32,34]])
print(a1)

[[ 2 23  0]
 [24 32 34]]


In [7]:
a2=np.zeros((3,4),dtype=np.int16)                   #生成一个三行四列的0矩阵
print(a2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
a3=np.empty((3,4))                                  #生成一个空矩阵，里面元素随机
print(a3)

[[-1.49166815e-154 -1.49166815e-154  9.88131292e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]]


In [9]:
a4=np.arange(10,20,2)                               #数列arange(start,args,kwargs)
print(a4) 

[10 12 14 16 18]


In [10]:
a5=np.arange(12).reshape((3,4))                     #生成三行四列 0-11 的数列,start和步长可以省略
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
a6=np.linspace(1,10,5)                              #生成 1-10 5段线段
print(a6)

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:

# numpy 基础运算


In [13]:
#数列运算
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
print(b<3)                                          #比较运算

[10 20 30 40] [0 1 2 3]
[ True  True  True False]


In [14]:
c=a-b                                               #数列四则运算（逐个对应运算）乘方（**）
print(c)

[10 19 28 37]


In [15]:
c1=10*np.sin(a)                                     #数列的三角函数运算
print(c1)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [17]:
#矩阵(二维数组)乘法
a=np.array([[1,1],
            [0,1]])
b=np.arange(4).reshape((2,2))

print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [18]:
c=a*b                                               #a*b:逐个相乘
c_dot=np.dot(a,b)                                   #np.dot(a,b): 矩阵乘法
c_dot_1=a.dot(b)                                    #equal to line66
print(c)
print(c_dot)
print(c_dot_1)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [19]:
a=np.random.random((2,4))                           
print(a)                                            #output是随机的两行四列的矩阵

print(np.sum(a,axis=1))                             #numpy中元素求和，axis=0:在行中操作； axis=1:在列中操作
print(np.min(a))                                    #numpy中元素求min
print(np.max(a))                                    #numpy中元素求max

[[0.84401168 0.93284866 0.94374939 0.08271897]
 [0.04957357 0.31757467 0.42514104 0.75583064]]
[2.80332869 1.54811993]
0.049573571803871896
0.9437493854276111


In [20]:
A=np.arange(2,14).reshape(3,4)
print(A)
print(np.argmin(A))                                 #最小值的索引
print(np.argmax(A))                                 #最大值的索引
print(np.average(A),A.mean())                       #计算平均值
print(np.median(A))                                 #计算中位数
print(np.cumsum(A))                                 #第i个元素是前i个数累加
print(np.diff(A))                                   #计算差值
print(np.nonzero(A))                                #输出矩阵中各个元素的行数与列数
print(np.sort(A))                                   #对数组A进行排序
print(np.transpose(A))                              #矩阵的转置
print(A.T)
print(np.clip(A,5,9))                               #保持5-9之间的数，<5的数变成5，>9的数变成9

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5 7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [21]:

#numpy 索引


In [23]:
A=np.arange(3,15).reshape(3,4)
print(A)

print(A[2])                                         #output: [11 12 13 14]
print(A[2,:])
print(A[1,:])
print(A[1][1])                                      #output: 8
print(A[1,1])                                       #output: 8

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
[11 12 13 14]
[ 7  8  9 10]
8
8


In [25]:
for row in A:
    print(row)

for column in A.T:
    print(column)

print(A.flatten())                                  # A.flatten():把多维数组展开成一维数组
for item in A.flat:
    print(item)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [26]:

#numpy array合并


In [28]:
A= np.array([1,1,1])
B= np.array([2,2,2])

C=np.vstack((A,B))                               #vertical stack:把两个数组合并成一个二维数组
print(C)  
print(A.shape,C.shape)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)


In [29]:
D=np.hstack((A,B))                                #horizontal stack：把两个数组合并成一个一维数组(可以多个数组进行合并）
print(D)                                         
print(A.shape,D.shape)


[1 1 1 2 2 2]
(3,) (6,)


In [30]:
#np.newaxis :增加维度
print(A[np.newaxis,:])                            #output: [[1 1 1]]
print(A[:,np.newaxis])                            #output为三维数组

[[1 1 1]]
[[1]
 [1]
 [1]]


In [31]:
A=np.array([1,1,1])[:,np.newaxis]
B=np.array([2,2,2])[:,np.newaxis]

C=np.concatenate((A,B,B,A),axis=1)                 #多个array进行横向合并（axis=0--纵向）
print(C)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [32]:

#numpy array 分割


In [34]:
A=np.arange(12).reshape(3,4)
print(A)

print(np.split(A,2,axis=1))                     #np.split(要分割的数组，分割完数组的个数，横向or纵向）--只能平均分割
print(np.array_split(A,2,axis=1))               #np.array_split( , , )--可以不等分割

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [35]:
print(np.vsplit(A,3))
print(np.hsplit(A,2))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [36]:

#numpy copy & deep copy  浅拷贝与深拷贝


In [37]:
a= np.arange(4)
print(a)

[0 1 2 3]


In [38]:
b = a                                 #深拷贝
c = a
d = b

In [39]:
a[0]=11                             #改变a中第一个元素
print(a)

[11  1  2  3]


In [40]:
print(b is a)
print(b,c,d)                        #b,c,d随之改变

True
[11  1  2  3] [11  1  2  3] [11  1  2  3]


In [41]:
d[1:3]=[22,33]                      #改变d中元素
print(d,a)                          #a 也随之改变

[11 22 33  3] [11 22 33  3]


In [42]:
b1=a.copy()                         #浅拷贝（指向的地址不同）
a[3]=44                             #改变a中元素
print(a,b1)                         #b1 不随a 改变

[11 22 33 44] [11 22 33  3]
